// Generated by LiveScript 1.2.0
var shoe, through, handlers;
window.IRBOT = {
  join: function(it){
    var x$, div;
    x$ = div = document.createElement('div');
    x$.id = 'roomlog';
    this.send("!join " + it);
    return document.body.appendChild(div);
  }
};
window.IRBOT.main = (shoe = require('shoe'), through = require('through'), handlers = {
  serverDc: function(){
    console.log("Server DC'd");
    return window.close();
  },
  log: function(it){
    return console.log(it.text);
  }
}, function(){
  var stream;
  stream = shoe('/irbot');
  stream.pipe(through(function(msg){
    var key$;
    msg = JSON.parse(msg);
    return typeof handlers[key$ = msg.event] === 'function' ? handlers[key$](msg) : void 8;
  }));
  delete window.IRBOT.main;
  return window.IRBOT.send = function(it){
    return stream.write(it);
  };
});